name: MacOs Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make MacOs
      run: |
        ./blackhosts --help
        sudo ./blackhosts -y
