name: MacOs Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make MacOs
      run: |
        echo ==================
        ./blackhosts --help
        echo ==================
        echo ==================
        sudo ./blackhosts -y
        echo ==================
        echo ==================
        cat /private/etc/hosts
        echo ==================
