name: MacOs Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Make MacOs
      run: |
        ./bin/unishellect.macos --help
        ./bin/unishellect.macos -c
        ./bin/unishellect.macos -c 'FAKEFILE'
        ./bin/unishellect.macos -m